{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "peertube.fullname" . }}
  labels:
    {{- include "peertube.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "peertube.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minimumReplicas }}
  maxReplicas: {{ .Values.autoscaling.maximumReplicas }}

  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.windowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.minCPUPercentage }}
        periodSeconds: 60

    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.windowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.minMemoryPercentage }}
        periodSeconds: 60

    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        periodSeconds: 15

    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
        periodSeconds: 20
  
  scaleTargetRef:
    kind: Deployment
    name: {{ include "peertube.fullname" . }}
    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}
{{- end }}
